# Xiaozhi Ball v1 — hardware pack (ESP32-S3 + GC9A01A round 240x240)

# --- BUSES / PERIPHERALS ------------------------------------------------------
spi:
  - id: spi_bus
    clk_pin: 14
    mosi_pin: 17
    # (no MISO line for display)

i2s_audio:
  - id: i2s_mic
    i2s_lrclk_pin: GPIO4   # WS
    i2s_bclk_pin:  GPIO5   # SCK
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO16
    i2s_bclk_pin:  GPIO15
    # (no MCLK on this board)

# --- AUDIO DEVICES ------------------------------------------------------------
microphone:
  - platform: i2s_audio
    id: box_mic
    i2s_audio_id: i2s_mic
    i2s_din_pin: GPIO6
    adc_type: external
    channel: left
    pdm: false
    sample_rate: 16000
    bits_per_sample: 16bit

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO7
    dac_type: external
    sample_rate: 16000
    channel: left

# --- BACKLIGHT ----------------------------------------------------------------
output:
  - platform: ledc
    id: backlight_output
    pin: GPIO3
    inverted: false

light:
  - platform: monochromatic
    id: Sled
    name: Screen
    icon: "mdi:television"
    entity_category: config
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# --- DISPLAY DRIVER (SPI GC9A01A, 240x240 round) ------------------------------
display:
  - platform: ili9xxx
    id: main_display
    model: GC9A01A
    spi_id: spi_bus
    cs_pin: 13
    dc_pin: 10
    reset_pin: 18
    invert_colors: true
    data_rate: 40MHz
    update_interval: never
    dimensions:
      height: ${imageheight}
      width: ${imagewidth}
    pages: !include ../display_pages.yaml

# --- BATTERY ADC --------------------------------------------------------------
sensor:
  - platform: adc
    pin: GPIO1
    name: "Battery Voltage"
    id: battery_voltage
    attenuation: 12db
    accuracy_decimals: 2
    update_interval: 10s
    unit_of_measurement: "V"
    icon: mdi:battery-medium
    filters:
      - multiply: 2.0
      - median:
          window_size: 7
          send_every: 7
          send_first_at: 1
      - throttle: 1min
    on_value:
      then:
        - sensor.template.publish:
            id: battery_percentage
            state: !lambda 'return x;'
