substitutions:
  name: esphome-web-6199a4
  friendly_name: Xiaozhi Muma Box v1

## Modular version v1.00 (all Muma versions)
## Split up the original yaml for easier maintance of many devices with different hardware.

## SETTINGS ######################################################################################################################################
  imagewidth:  "240"
  imageheight: "240"

  startup_sound: "Home_Connected" # (options are: available, Home_ Connected, Home_ Connected_Male, Computer_Ready)
  clock_background_image: "clock" # (options are: clock, hacker, ha-girl, mission, starrysky)
  imagemodel: "Gwen" # options are:

# Alita, Alfred, Astrobot, Buzz, Casita, Cybergirl, Dory, EVE, Eyes, Eyes2, GLaDOS, Girl1, Guy1, Guy2, Gwen, HA-character, ha-girl, Hacker, Harley,
# Jarvis, Luffy, Mario, Max, Prime, Robochibi, Robocop, Robot, Robotgirl, Shaun
##################################################################################################################################################

  font_glyphsets: "GF_Latin_Core"
  font_family: Figtree

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

packages:
  core:
    url: https://github.com/RealDeco/xiaozhi-esphome.git
    ref: main
    refresh: 1d
    files:
      - devices/Under_Development/Modular/core.yaml
  hw:
    url: https://github.com/RealDeco/xiaozhi-esphome.git
    ref: main
    refresh: 1d
    files:
      - devices/Under_Development/Modular/HW/muma_hw.yaml
