# ============================================================================
# FILE: devices/Under_Development/Modular/spotify.yaml
# ============================================================================

text_sensor:
  - platform: homeassistant
    id: spotify_title
    entity_id: sensor.spotify_title
    internal: true
    
  - platform: homeassistant
    id: spotify_artist
    entity_id: sensor.spotify_artist
    internal: true
    
  - platform: homeassistant
    id: spotify_album
    entity_id: sensor.spotify_album
    internal: true
    
  - platform: homeassistant
    id: spotify_album_art_url
    entity_id: sensor.spotify_album_art
    internal: true
    on_value:
      then:
        - script.execute: update_spotify_image

binary_sensor:
  - platform: homeassistant
    id: spotify_is_playing
    entity_id: binary_sensor.spotify_playing
    internal: true

sensor:
  - platform: homeassistant
    id: spotify_volume
    entity_id: sensor.spotify_volume
    internal: true
    
  - platform: homeassistant
    id: spotify_position
    entity_id: sensor.spotify_position
    internal: true
    
  - platform: homeassistant
    id: spotify_duration
    entity_id: sensor.spotify_duration
    internal: true

online_image:
  - id: spotify_album_art
    url: https://i.scdn.co/image/ab67616d0000b273e319baafd16e84f0408af2a0
    resize: 160x160
    format: JPEG
    type: RGB565
    update_interval: never
    on_download_finished:
      - lambda: |-
          ESP_LOGI("spotify", "Album art downloaded successfully");
      - if:
          condition:
            lambda: 'return id(show_spotify_page);'
          then:
            - delay: 100ms
            - component.update: main_display
    on_error:
      - lambda: |-
          ESP_LOGE("spotify", "Failed to download album art");

font:
  - file:
      type: gfonts
      family: ${font_family}
      weight: 700
    id: spotify_title_font
    size: 16
    glyphsets:
      - ${font_glyphsets}
    ignore_missing_glyphs: true
    
  - file:
      type: gfonts
      family: ${font_family}
      weight: 400
    id: spotify_artist_font
    size: 13
    glyphsets:
      - ${font_glyphsets}
    ignore_missing_glyphs: true
    
  - file:
      type: gfonts
      family: ${font_family}
      weight: 400
    id: spotify_small_font
    size: 11
    glyphsets:
      - ${font_glyphsets}
    ignore_missing_glyphs: true

color:
  - id: spotify_green
    hex: "1ED760"
  - id: spotify_dark
    hex: "121212"
  - id: spotify_grey
    hex: "B3B3B3"

globals:
  - id: show_spotify_page
    type: bool
    restore_value: no
    initial_value: "false"

script:
  - id: update_spotify_image
    then:
      - if:
          condition:
            lambda: |-
              return id(spotify_album_art_url).has_state() && 
                     id(spotify_album_art_url).state.length() > 10;
          then:
            - lambda: |-
                ESP_LOGD("spotify", "Image path: %s", id(spotify_album_art_url).state.c_str());
            - online_image.set_url:
                id: spotify_album_art
                url: !lambda |-
                  return std::string("https://ha.liminal.net.au") + id(spotify_album_art_url).state;

  - id: open_spotify_page
    mode: restart
    then:
      - lambda: |-
          ESP_LOGD("spotify", "Opening Spotify page");
          id(show_spotify_page) = true;
          id(show_clock) = false;
      - script.execute: reset_screensaver
      - script.execute: update_spotify_image
      - delay: 1500ms
      - display.page.show: spotify_page
      - component.update: main_display

  - id: close_spotify_page
    mode: restart
    then:
      - lambda: |-
          ESP_LOGD("spotify", "Closing Spotify page");
          id(show_spotify_page) = false;
      - script.execute: draw_display

switch:
  - platform: template
    id: spotify_auto_show
    name: "Spotify Auto Show"
    icon: "mdi:spotify"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config

interval:
  - interval: 5s
    then:
      - if:
          condition:
            lambda: 'return id(show_spotify_page);'
          then:
            - component.update: main_display