substitutions:
  # Hardware v2 pin mappings
  sda_pin: "15"
  scl_pin: "14"
  led_pin: "48"
  i2s_lrclk_pin: "45"
  i2s_bclk_pin: "9"
  i2s_mclk_pin: "16"
  i2s_din_pin: "10"
  i2s_dout_pin: "8"
  speaker_enable_pin: "46"
  left_top_button_pin: "0"
  touch_input_pin: "12"
  backlight_output_pin: "42"
  lcd_cs_pin: "5"
  lcd_dc_pin: "47"
  lcd_reset_pin: "38"
  spi_clk_pin: "4"
  spi_mosi_pin: "2"
  battery_adc_pin: "1"
